# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BYPcbrUMaGM00seiCcOHZGbMQF3d37W8
"""

import numpy as np
import pandas as pd

df=pd.read_csv('/content/CAR DETAILS FROM CAR DEKHO.csv')
df

df.shape

df.duplicated()

df.drop_duplicates(inplace=True)

df.shape

df.head()

df.tail()

df.isna().sum()

df.dtypes

df['brand']=df['name'].apply(lambda x:x.split()[0])
df

df.drop(['name'],axis=1,inplace=True)
df

df['brand'].value_counts()

df.dtypes

from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
df['brand']=lb.fit_transform(df['brand'])
df['fuel']=lb.fit_transform(df['fuel'])
df['seller_type']=lb.fit_transform(df['seller_type'])
df['transmission']=lb.fit_transform(df['transmission'])
df['owner']=lb.fit_transform(df['owner'])
df